### ISSUE TITLE
Full Name, Affiliation (Department) and Email You want on the paper

### ISSUE THREAD

**Issue by rambasnet** [rambasnet/DeepLearning-IDS#10]
Can you email me those to complete the paper? Ray, you can use your CU Boulder affiliation.
I need them sooner to complete the paper. Also, Ray are you keeping an eye on the CPU experiment running in CRL server?

**Comment by Blackbird002** [comment]
The fastai binaryclass just finished with an elapsed time of 19441.55 minutes or ~ 13.5 days. I pushed the result and updated the README with the time. Do you want to run the multiclass fastai experiment next on VM CPU? It will be another >=13 days to complete.

**Comment by rambasnet** [comment]
Thanks  for the update, Ray! Yes, plz let it run so we can put the results
when we’ll be asked to resubmit which may take 4 to 6 weeks.
