### ISSUE TITLE
fast.ai summary results typo?

### ISSUE THREAD

**Issue by rambasnet** [rambasnet/DeepLearning-IDS#4]
02-16-2018.csv | 99.97% | 324160
-- | -- | --

Is loss correct for this row?

**Comment by JohnsonClayton** [comment]
From what my logs say, that table is accurate. I am currently rerunning 02-16 for this reason.

**Comment by JohnsonClayton** [comment]
Newest run returned a loss of 4111.4843, not sure why it's so high.
