### ISSUE TITLE
create confusion matrices

### ISSUE THREAD

**Issue by rambasnet** [rambasnet/DeepLearning-IDS#5]
create confusion matrices for multi-class and binary-class experiments (from one experiment is good)

**Comment by JohnsonClayton** [comment]
I will try. The only model I have for both is epoch 9 on fold 5.

**Comment by JohnsonClayton** [comment]
Currently don't have resources to pull the confusion matrix. I will discuss with Ray if we can use the GPU set up to evaluate it.

**Comment by Blackbird002** [comment]
Done, please see
 https://github.com/rambasnet/DeepLearning-IDS/tree/master/graphics/confusion_matrices 
folder. I made the image size bigger for IDS-2018-multiclass to nicely fit all the classes and to prevent overlap.

**Comment by rambasnet** [comment]
Great, thanks!

**Comment by rambasnet** [comment]
Ray, actually can you create the Binary-class image a little smaller so it doesn't cutoff horizontal label and change 0 as Benign and 1 as Attack?

**Comment by Blackbird002** [comment]
I have made the necessary changes and also fixed the multi-class horizontal label cutoff.

**Comment by rambasnet** [comment]
@Blackbird002 Good job!
