### ISSUE TITLE
GPU Times

### ISSUE THREAD

**Issue by rambasnet** [rambasnet/DeepLearning-IDS#7]
Make sure to record GPU times for each experiment

**Comment by Blackbird002** [comment]
Okay, will do.

**Comment by rambasnet** [comment]
GPU time seems to be much higher compared to CPU that I had noted. Can you record the CPU times on the same system for the same experiments as well?

**Comment by Blackbird002** [comment]
The data from table labeled "Using CPU" are actually results using Salamander.ai cloud service that uses a GPU (Nvidia K80). I updated the README to clarify that. I also added a table comparing fastai training times using CPU & GPU from vmGPU (our VM in the lab that uses gpu).  I will update the table as more CPU fastai results come in.
